### ISSUE TITLE
Unable to run quick start -- Error: Cannot find module 'commander'

### ISSUE THREAD

**Issue by deinspanjer** [Qiksar/crudio#5]
I'm running on OSX. My NPM/NPX version is 8.19.2 installed by default via `brew install node` which installs Node 18.11.0.

When I run ` npx @qiksar/crudio@latest -v -p crudio_test` or `wget -O - https://raw.githubusercontent.com/qiksar/crudio/main/tools/init.sh | bash` or the last command of that init.sh script, `npx -y @qiksar/crudio@latest -v -w -m datamodel/datamodel.json -i repo/iot.json` I get the following error:
```node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'commander'
Require stack:
- /Users/daniel.e/.npm/_npx/451bd001371c3093/node_modules/@qiksar/crudio/lib/CrudioCLI.js
- /Users/daniel.e/.npm/_npx/451bd001371c3093/node_modules/@qiksar/crudio/lib/crudio_cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/daniel.e/.npm/_npx/451bd001371c3093/node_modules/@qiksar/crudio/lib/CrudioCLI.js:4:21)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/daniel.e/.npm/_npx/451bd001371c3093/node_modules/@qiksar/crudio/lib/CrudioCLI.js',
    '/Users/daniel.e/.npm/_npx/451bd001371c3093/node_modules/@qiksar/crudio/lib/crudio_cli.js'
  ]
}

Node.js v18.11.0
```

**Comment by deinspanjer** [comment]
further information. I eventually tried running the previous version 0.21 and got past that commander error.
I looked at a github diff between the 21 and 22 branches, and it looks like commander-ts was moved from a normal dependency to a dev dependency, so I suspect that is the source of the problem.

**Comment by chrisnurse** [comment]
many thanks for the detailed feedback, and apologies for the slow reponse.
I just moved command to the normal dependencies, and pushed the new change.
Could you please pull and retest.

**Comment by chrisnurse** [comment]
@deinspanjer thank you once again for raising this issue. Man it started a real journey into so many issues in the quick start process, i.e. running:

wget -O - https://raw.githubusercontent.com/qiksar/crudio/main/tools/init.sh | bash

Long story short, it's fixed now. Sorry it took so long to get to the bottom of this.

All the best for the thanksgiving period ahead.

C
